export const articleCategories: string[] = [
  "JavaScript",
  "TypeScript",
  "HTML",
  "CSS",
  "React",
  "Angular",
  "Vue",
  "Svelte",
  "Python",
  "Django",
  "Java",
  "Spring & Spring Boot",
  "C# & .NET",
  "C++",
  "Ruby",
  "Ruby on Rails",
  "PHP",
  "Laravel",
  "Kotlin",
  "Swift",
  "Node.js",
  "Express.js",
  "Databases",
  "Networking & APIs",
  "State management",
  "Microservices",
  "Git & Version control",
  "Testing",
  "Docker & Containers",
  "Cloud platforms",
  "Security",
  "Performance",
  "UX/UI",
  "Dev life",
  "Culture & Community",
  "Other",
];
