import { FormFieldConfig } from "../types";

export const formFields: FormFieldConfig = {
  firstName: {
    name: "firstName",
    id: "firstName",
    label: "First name *",
    type: "text",
    placeholder: "First name",
    required: true,
  },
  lastName: {
    name: "lastName",
    id: "lastName",
    label: "Last name *",
    placeholder: "Last name",
    type: "text",
    required: true,
  },
  email: {
    name: "email",
    id: "email",
    label: "Email *",
    placeholder: "Email",
    type: "email",
    required: true,
  },
  password: {
    name: "password",
    id: "password",
    label: "Password *",
    placeholder: "Password",
    type: "password",
    required: true,
  },
  repeatPassword: {
    name: "repeatPassword",
    id: "repeatPassword",
    label: "Repeat password *",
    placeholder: "Repeat password",
    type: "password",
    required: true,
  },
  newPassword: {
    name: "newPassword",
    id: "newPassword",
    label: "New password *",
    placeholder: "New password",
    type: "password",
    required: true,
  },
  repeatNewPassword: {
    name: "repeatNewPassword",
    id: "repeatNewPassword",
    label: "Repeat new password *",
    placeholder: "Repeat new password",
    type: "password",
    required: true,
  },
  acceptTerms: {
    name: "acceptTerms",
    id: "acceptTerms",
    label: "I have read and accept the Terms of Use",
    type: "checkbox",
    required: true,
  },
};
